packageExtensions:
  "@commitlint/cli@*":
    peerDependencies:
      typescript: "*"
      "@types/node": "*"
  "@commitlint/load@*":
    peerDependencies:
      typescript: "*"
      "@types/node": "*"
  "@stylistic/eslint-plugin@*":
    peerDependencies:
      typescript: "*"
  eslint-plugin-perfectionist@*:
    peerDependencies:
      typescript: "*"

tsEnableAutoTypes: false
