name: pages
on:
  push:
    branches:
      - 'master'
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: yarn doc
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './public/'
      - uses: actions/deploy-pages@v4
