name: publish
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: yarn build-release
      - run: yarn npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
